### ISSUE TITLE
Enable configurable view engines

### ISSUE THREAD

**Issue by federicobond** [originalmachine/edict#1]
The ability to plug in a custom view engine would decouple `edict` from `nunjucks` and provide greater flexibility for other users. Let me know if you are interested so I can submit a pull request.

**Comment by secretfader** [comment]
Totally. Go for it! Just make sure to properly implement the cache (which Nunjucks has built in - so I didn't need to build it out myself.)

Maybe on top of consolidate? (I think it has view caching built in, so this should be fairly easy to implement.)
